### PR TITLE
fixed specdm and other things

### PR DESCRIPTION
**Pull request by mexikoedi**
added checks and fixed noLag console error if the shinigami is in spectator deathmatch, (look comment below)

### CODE REVIEW

**Comment by TimGoll** [comment]
Please remove unnecessary spaces around brackets and replace `== false` with `not`

**Comment by saibotk** [comment]
What is this `IsGhost` function? This will only throw errors if it does not exist, also i don't want to change the respawn behavior, as it is intended in the way this is.

**Comment by mexikoedi** [comment]
IsGhost is from specdm. Without it the shinigami will not work with the specdm and also will throw the nolag error. Also it is kind of weird if the shinigami kills himself and then respawns. That is fixed too.

**Comment by saibotk** [comment]
As i already said, you are using the function and it will throw an error for people not running spec dm.
Also as i said, there is no need to "fix" the respawn behavior as i do not want it to be like that.

**Comment by ZacharyHinds** [comment]
Yeah to reiterate saibotk, I ran into a similar issue with my Spectre, if they don't have SpecDM installed it will throw an error

**Comment by saibotk** [comment]
@ZacharyHinds can be fixed if you also check for the availability of the function with `ply.IsGhost`

**Comment by Alf21** [comment]
like `(not ply.IsGhost or not ply:IsGhost())`

**Pull request closed without merging**
